http://localhost:3100/users

###separate request

http://localhost:3100/users/1

###
http://localhost:3100/posts


###
http://localhost:3100/posts/1
NP-Demo: Best Class Ever

###
POST http://localhost:3100/posts/
Content-Type: application/json

{
    "src": "https://api.nasa.gov/planetary/apod?api_key=te2AWQonPBWdmeQwm3eutLVyZ1eAZbHBWeFvbw1H",
    "alt": "A Waterfall and the Milkyway",
    "caption": "A Waterfall and the Milkyway",
    "user_handle": "@JewPaltz",
    "isPublic": true

}
###
https://api.nasa.gov/planetary/apod?api_key=te2AWQonPBWdmeQwm3eutLVyZ1eAZbHBWeFvbw1H


###
http://localhost:3100/posts/search?q=the


